name: "decoder"
platform: "tensorrt_plan"
max_batch_size: 0
input [
    {
    name: "tgt_inp"
    data_type: TYPE_INT32
    dims: [-1, -1]
    },
    {
    name: "encoder_hidden_states"
    data_type: TYPE_FP32
    dims: [257, -1, 256]
    }
]
output [
    {
    name: "output_decoder"
    data_type: TYPE_INT32
    dims: [-1]
  }
]

default_model_filename: "decoder_merge.plan" 